spring.application.name: WebConsumer

server.port: 8090

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 10000
        failureRateThreshold: 60
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
    instances:
      HelloConsumerCircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 50s
        permittedNumberOfCallsInHalfOpenState: 1
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


  retry:
    instances:
      HelloConsumerCircuitBreaker:
        maxRetryAttempts: 1
        waitDuration: 10s